### ISSUE TITLE
When exporting a GDevelop game project to the web using gdcore-tools, certain game elements don’t function as expected

### ISSUE THREAD

**Issue by jasmeenPedalsup** [arthuro555/gdcore-tools#7]
When exporting a GDevelop game project to the web using gdcore-tools, certain game elements don’t function as expected. Specifically:

1. Object movement (auto moving object in scene) doesn’t work in the exported web build.
2. The Score variable doesn’t update on the UI layer as intended.
3. Mouse clicks not wokring

**Steps to Reproduce**

1. Create a GDevelop project and save it as a JSON file.(take any existing game template like plinko, platformer or any other)
2. Use the following Node.js code to export the project:
3. Open the exported web build and observe the game’s functionality.

```
import { exportProject, loadProject } from "gdcore-tools";

async function loadGD() {
  try {
    const project = await loadProject("./mygame/game.json");
    await exportProject(project, "./build", "web");
  } catch (err) {
    console.error("Error processing the file:", err);
  }
}

loadGD();
```

**Expected Behavior**

The game should have full functionality as it does in the GDevelop IDE, including:

-   Smooth object movement.
-   Real-time updating of score in the UI layer.

**Actual Behavior**

-   Objects are stationary and do not move as expected.
-   The score UI element does not update.

**Environment**

GDevelop Version: 5.4.217
gdcore-tools Version: 2.0.0-beta1
Node.js Version: v20.14.0
Operating System: Ubuntu

**Comment by arthuro555** [comment]
Please try the latest version of `gdcore-tools` (beta7)

**Comment by jasmeenPedalsup** [comment]
I tried using beta7 version but I am still facing issues below is json file for plinko game
[https://drive.google.com/file/d/1pBSEQvWAz0r3ZUsh_zL7zxH2lqNbN7qb/view?usp=sharing](https://drive.google.com/file/d/1pBSEQvWAz0r3ZUsh_zL7zxH2lqNbN7qb/view?usp=sharing)

if I open this file in online IDE then It's working perfectly but when I export game using gdcore-tool then still I am facing above listed issues

**Comment by jasmeenPedalsup** [comment]
`gdcore-tools Version: 2.0.0-beta9` solve this issue.
